config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :book_reservations
  resources :book_returns
  resources :book_issues
  get 'transactions/details'
  get 'transactions/view_more'
  get 'book_issues/new'
  get 'book_returns/new'
  get 'book_reservations/new'
  get 'library/index'
  get 'library/books'
  get 'library/school_library'
  get 'library/rules_regulation'
  get 'users/login'

  resources :library
  resources :book_transaction
  resources :users

root 'library#index'

end

app/models/book_reservation.rb
class BookReservation < ActiveRecord::Base
end

app/controllers/book_reservations_controller.rb
class BookReservationsController < ApplicationController
  before_action :set_book_reservation, only: [:show, :edit, :update, :destroy]

  # GET /book_reservations
  # GET /book_reservations.json
  def index
    @book_reservations = BookReservation.all
  end

  # GET /book_reservations/1
  # GET /book_reservations/1.json
  def show
  end

  # GET /book_reservations/new
  def new
    @book_reservation = BookReservation.new
  end

  # GET /book_reservations/1/edit
  def edit
  end

  # POST /book_reservations
  # POST /book_reservations.json
  def create
    @book_reservation = BookReservation.new(book_reservation_params)

    respond_to do |format|
      if @book_reservation.save
        format.html { redirect_to @book_reservation, notice: 'Book reservation was successfully created.' }
        format.json { render :show, status: :created, location: @book_reservation }
      else
        format.html { render :new }
        format.json { render json: @book_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reservations/1
  # PATCH/PUT /book_reservations/1.json
  def update
    respond_to do |format|
      if @book_reservation.update(book_reservation_params)
        format.html { redirect_to @book_reservation, notice: 'Book reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_reservation }
      else
        format.html { render :edit }
        format.json { render json: @book_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reservations/1
  # DELETE /book_reservations/1.json
  def destroy
    @book_reservation.destroy
    respond_to do |format|
      format.html { redirect_to book_reservations_url, notice: 'Book reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_reservation
      @book_reservation = BookReservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_reservation_params
      params.require(:book_reservation).permit(:bookName, :firstName, :middlename, :lastName, :student_id_no, :dateReservation)
    end
end

app/helpers/book_reservations_helper.rb
module BookReservationsHelper
end

app/views/book_reservations/_form.html.erb
<div class="container">

<%= form_for(@book_reservation) do |f| %>
  <% if @book_reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_reservation.errors.count, "error") %> prohibited this book_reservation from being saved:</h2>

      <ul>
      <% @book_reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :book_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :bookName, :placeholder => "Book Name" %>
    </div>
  </div><br/>

  <!--<div class="field">-->
    <!--<div class="col-md-2">-->
      <!--<%= f.label :book_Number %>-->
    <!--</div>-->
    <!--<div class="col-md-2">-->
      <!--<%= f.text_field :bookNumber, :placeholder => "Book Number" %>-->
    <!--</div>-->
  <!--</div><br/>-->

  <div class="field">
    <div class="col-md-2">
      <%= f.label :first_Name %>
    </div>
    <div class="col-md-2">
      <%= current_user.firstname %>
      <%= f.text_field :firstName, :value => current_user.firstname, :placeholder => "First Name", :type => "hidden" %>
    </div>
  </div><br/>

      <div class="field">
        <div class="col-md-2">
          <%= f.label :middle_Name %>
        </div>
        <div class="col-md-2">
          <%= current_user.middlename %>
          <%= f.text_field :miidleName, :value => current_user.middlename, :placeholder => "Middle Name", :type => "hidden" %>
        </div>
      </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :last_Name %>
    </div>
    <div class="col-md-2">
      <%= current_user.lastname %>
      <%= f.text_field :lastName, :value => current_user.lastname, :placeholder => "Last Name", :type => "hidden" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :student_id_no %>
    </div>
    <div class="col-md-2">
      <%= current_user.student_id_no %>
      <%= f.text_field :student_id_no, :value => current_user.student_id_no, :placeholder => "Student Id No.", :type => "hidden" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :date_Reservation %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :dateReservation, :placeholder => "mm/dd/yy" %>
    </div>
  </div><br/><br/><br/>

  <div class="actions">
    <%= f.submit class: "btn-success"%>
  </div>
<% end %>
  </div>

app/views/book_reservations/edit.html.erb
<div class="container">
  <div class="container">
    <!--<ul class="kj">-->
      <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
      <!--<li class="li"><%= link_to 'Book Issue', book_issues_new_path %></li>-->
      <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
      <!--<li class="li"><%= link_to 'Book Reservation' %></li>-->
    <!--</ul>-->
  </div>
  <br><br>
  <div class="hover col-md-12">
<h1>Editing Book Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_reservation %> |
<%= link_to 'Back', book_reservations_path %>
</div>
</div>

app/views/book_reservations/index.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue', book_issues_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation' %></li>-->
  <!--</ul>-->
</div>
<br><br>
<div class="container">
  <div class="hover col-md-12">

<p id="notice"><%= notice %></p>

<h1 class="text-center">Listing Book Reservations</h1>
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="f">Book Name</th>
      <!--<th class="f">Book Number</th>-->
      <th class="f">First Name</th>
      <th class="f">Middle Name</th>
      <th class="f">Last Name</th>
      <th class="f">Student id no</th>
      <th class="f">Date Reservation</th>
      <th colspan="3" class="f">Option</th>
    </tr>
  </thead>

  <tbody>
    <% @book_reservations.each do |book_reservation| %>
      <tr>
        <td><%= book_reservation.bookName %></td>
        <!--<td><%= book_reservation.bookNumber %></td>-->
        <td><%= book_reservation.firstName %></td>
        <td><%= book_reservation.middlename %></td>
        <td><%= book_reservation.lastName %></td>
        <td><%= book_reservation.student_id_no %></td>
        <td><%= book_reservation.dateReservation %></td>
        <td class="f"><%= link_to 'Show', book_reservation, class: "btn btn-info" %></td>
        <td class="f"><%= link_to 'Edit', edit_book_reservation_path(book_reservation), class: "btn btn-warning" %></td>
        <td class="f"><%= link_to 'Destroy', book_reservation, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'New Book reservation', new_book_reservation_path, class: "btn btn-primary" %></strong><br><br>
  </div>
</div>

<br><br><br><br><br><br>

app/views/book_reservations/new.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue',book_issues_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path%></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation'%></li>-->
  <!--</ul>-->
</div>
<br><br><br><br>

<div class="container">
  <div class="well">
    <table class="table table-responsive">
      <thead>
      <div>
        <p class="h1 text-center">SMNHS LIBRARY SYSTEM</p>
      </div>
      <div>
        <p colspan="5" class="h2 text-center">Book Reservations</p>
      </div>
      </thead>
      <tbody>
      <div class="col-md-12">
        <div class="col-md-6 hover"><br/><br/><br/>

          <%= render 'form' %><br/>

        </div><br><br/><br/>
        <div class="col-md-6">
          <div class="col-md-12">
            <div class="center-block">
              <div class="well alert-danger">
                <h2>Reminder:</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nam
                  possimus veniam? Commodi delectus error est explicabo illo itaque provident
                  ratione rem tenetur veritatis. Ad est explicabo facere impedit nemo.</p>
              </div>
            </div>
            <%= link_to 'Show the Book Reservation >>', book_reservations_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      </tbody>
    </table>
  </div>
</div>

</div>

app/views/book_reservations/show.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue', book_issues_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation'%></li>-->
  <!--</ul>-->
</div>
<br><br>
<div class="container">
<div class="hover col-md-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookname:</strong>
  <%= @book_reservation.bookName %>
</p>
  <br>
<!--<p>-->
  <!--<strong>Booknumber:</strong>-->
  <!--<%= @book_reservation.bookNumber %>-->
<!--</p>-->
  <br>
<p>
  <strong>Firstname:</strong>
  <%= @book_reservation.firstName %>
</p>
  <br>
  <p>
    <strong>Middlename:</strong>
    <%= @book_reservation.middlename %>
  </p>
  <br>
<p>
  <strong>Lastname:</strong>
  <%= @book_reservation.lastName %>
</p>
  <br>
<p>
  <strong>Student id no:</strong>
  <%= @book_reservation.student_id_no %>
</p>
  <br>
<p>
  <strong>Datereservation:</strong>
  <%= @book_reservation.dateReservation %>
</p>
  <br>
<%= link_to 'Edit', edit_book_reservation_path(@book_reservation) %> |
<%= link_to 'Back', book_reservations_path %>
</div>
</div>
<br><br><br>