config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :book_reservations
  resources :book_returns
  resources :book_issues
  get 'transactions/details'
  get 'transactions/view_more'
  get 'book_issues/new'
  get 'book_returns/new'
  get 'book_reservations/new'
  get 'library/index'
  get 'library/books'
  get 'library/school_library'
  get 'library/rules_regulation'
  get 'users/login'

  resources :library
  resources :book_transaction
  resources :users

root 'library#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
end

app/models/book_issue.rb
class BookIssue < ActiveRecord::Base
end

app/models/book_reservation.rb
class BookReservation < ActiveRecord::Base
end

app/models/book_return.rb
class BookReturn < ActiveRecord::Base
end

app/models/return.rb
class Return < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # private
  # def user_params
  #   params.require(:user).permit(:lastname, :firstname, :middlename)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :photo)
    end
end

app/controllers/isssues_controller.rb
class IsssuesController < ApplicationController
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def show
    @library = Library.new
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    signed_in? && current_user.role == 'admin'
  end

  def student?
    signed_in? && current_user.role == 'student'
  end
end

app/helpers/book_issues_helper.rb
module BookIssuesHelper
end

app/helpers/book_reservations_helper.rb
module BookReservationsHelper
end

app/helpers/book_returns_helper.rb
module BookReturnsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/isssues_helper.rb
module IsssuesHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/details.html.erb
<div class="container"></br>
    <div class="col-md-12 hover">
        <div class="col-md-3 margin">
          <div>
            <img src="/assets/books/downloyufdad.jpg" alt="img"/>
          </div>
          <br>
          <div class="kj">
            <p>Title: <strong>Science I Book</strong></p>
            <%= link_to "Issued", book_issues_new_path%> |
            <%= link_to "Return", book_returns_new_path %> |
            <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
          </div>
        </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/biology.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Science II Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path%> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/chemistry2.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Science III Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path%> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/science_book.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Science IV Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/mapeh.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Mapeh I Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/mapeh.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Mapeh II Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div><br/>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/mapeh.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Mapeh III Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/mapeh.jpg" alt="img"/>
        </div>
        <br>
        <div class="kj">
          <p>Title: <strong>Mapeh IV Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/biology.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/biology.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/biology.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/biology.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/Math.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/Math.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/Math.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/Math.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/chemistry2.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/chemistry2.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/chemistry2.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <div class="col-md-3 margin">
        <div>
          <img src="/assets/books/chemistry2.jpg" alt="img"/>
        </div>
        <div class="kj">
          <p>Title: <strong>Science Book</strong></p>
          <%= link_to "Issued", book_issues_new_path%> |
          <%= link_to "Return", book_returns_new_path %> |
          <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
        </div>
      </div>
      <%= link_to 'View More', transactions_view_more_path %>
      <br><br>
    </div>
</div>
<br/>

app/views/transactions/view_more.html.erb
<div class="container"></br>
  <div class="col-md-12 hover">
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/science_book.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/science_book.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path%> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/science_book.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path%> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/science_book.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/mapeh.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/mapeh.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div><br/>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/mapeh.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/mapeh.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/biology.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/biology.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/biology.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/biology.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/Math.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/Math.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/Math.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/Math.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/chemistry2.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/chemistry2.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/chemistry2.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <div class="col-md-3 margin">
      <div>
        <img src="/assets/books/chemistry2.jpg" alt="img"/>
      </div>
      <div class="kj">
        <p>Title: <strong>Science Book</strong></p>
        <%= link_to "Issued", book_issues_new_path%> |
        <%= link_to "Return", book_returns_new_path %> |
        <%= link_to "Reserve", book_reservations_new_path %><br/><br/>
      </div>
    </div>
    <br><br>
  </div>
</div>
<br/>