config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :book_reservations
  resources :book_returns
  resources :book_issues
  get 'transactions/details'
  get 'transactions/view_more'
  get 'book_issues/new'
  get 'book_returns/new'
  get 'book_reservations/new'
  get 'library/index'
  get 'library/books'
  get 'library/school_library'
  get 'library/rules_regulation'
  get 'users/login'

  resources :library
  resources :book_transaction
  resources :users

root 'library#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
end

app/models/book_issue.rb
class BookIssue < ActiveRecord::Base
end

app/models/book_reservation.rb
class BookReservation < ActiveRecord::Base
end

app/models/book_return.rb
class BookReturn < ActiveRecord::Base
end

app/models/return.rb
class Return < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # private
  # def user_params
  #   params.require(:user).permit(:lastname, :firstname, :middlename)
  # end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :photo)
    end
end

app/controllers/isssues_controller.rb
class IsssuesController < ApplicationController
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def show
    @library = Library.new
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    signed_in? && current_user.role == 'admin'
  end

  def student?
    signed_in? && current_user.role == 'student'
  end
end

app/helpers/book_issues_helper.rb
module BookIssuesHelper
end

app/helpers/book_reservations_helper.rb
module BookReservationsHelper
end

app/helpers/book_returns_helper.rb
module BookReturnsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/isssues_helper.rb
module IsssuesHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LibrarySystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="nav navbar navbar-default">
    <img src="/assets/smnhs.png" class="img">
    <div class="container">
      <div class="navbar-header">
        <button class=" navbar-toggle" data-toggle="collapse" data-target="#navbarToggle">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div>

        </div>
      </div>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <ul class="navbar-nav navbar-right kj">

          <%if signed_in?%>
              <li class="li"><a href="#">Account <span class="caret"></span></a>
                <ul class="kj">
                  <li class="li border" style="color: #eaf6ff; background: rgba(255, 33, 229, 0.42)"><%=link_to current_user.email, edit_user_registration_path%></li>
                  <li class="li"><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
                </ul>
              </li>



          <li class="li"><a href="#">About <span class="caret"></span></a>
            <ul class="kj">
              <li class="li border"><%= link_to 'Books', library_books_path %></li>
              <li class="li border"><%= link_to 'School Library', library_school_library_path %></li>
              <li class="li"><%= link_to 'Rules and Regulations', library_rules_regulation_path %></li>
            </ul>
          </li>
              <li class="li"><a href="#">Books Transaction <span class="caret"></span></a>
                <ul class="kj">
                  <% if admin? %>
                      <li class="li border"><%= link_to 'Book Details', books_path %></li>
                      <li class="li border"><%= link_to 'Book Issue', book_issues_new_path %></li>
                      <li class="li border"><%= link_to 'Book Returns', book_returns_new_path %></li>
                      <li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>
                  <% elsif student? %>
                      <li class="li border"><%= link_to 'Book Details', books_path %></li>
                      <li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>
                  <% else %>
                      <li class="li border"><%= link_to 'Book Details', books_path %></li>
                      <li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>
                  <% end %>
                </ul>
              </li>
              <li class="li"><%= link_to 'Home', library_index_path %></li>

        </ul>



          <%else%>
              <li class="li ul"><%=link_to "Sign-up", new_user_registration_path%></li>
              <li class="li ul"><%=link_to "Login", new_user_session_path%></li>
          <%end%>

      </div>
    </div>
  </nav>

<%= yield %>

  <div class="panel-footer footer">
    <p class="text-center">Copyright &copy; @ your Website 2015 All Rights reserved 2015</p>
  </div>
</body>
</html>