config/routes.rb
Rails.application.routes.draw do
  resources :books

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :book_reservations
  resources :book_returns
  resources :book_issues
  get 'transactions/details'
  get 'transactions/view_more'
  get 'book_issues/new'
  get 'book_returns/new'
  get 'book_reservations/new'
  get 'library/index'
  get 'library/books'
  get 'library/school_library'
  get 'library/rules_regulation'
  get 'users/login'

  resources :library
  resources :book_transaction
  resources :users

root 'library#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
end

app/models/book_issue.rb
class BookIssue < ActiveRecord::Base
end

app/models/book_reservation.rb
class BookReservation < ActiveRecord::Base
end

app/models/book_return.rb
class BookReturn < ActiveRecord::Base
end

app/models/return.rb
class Return < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # private
  # def user_params
  #   params.require(:user).permit(:lastname, :firstname, :middlename)
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/book_issues_controller.rb
class BookIssuesController < ApplicationController
  before_action :set_book_issue, only: [:show, :edit, :update, :destroy]

  # GET /book_issues
  # GET /book_issues.json
  def index
    @book_issues = BookIssue.all
  end

  # GET /book_issues/1
  # GET /book_issues/1.json
  def show
  end

  # GET /book_issues/new
  def new
    @book_issue = BookIssue.new
  end

  # GET /book_issues/1/edit
  def edit
  end

  # POST /book_issues
  # POST /book_issues.json
  def create
    @book_issue = BookIssue.new(book_issue_params)

    respond_to do |format|
      if @book_issue.save
        format.html { redirect_to @book_issue, notice: 'Book issue was successfully created.' }
        format.json { render :show, status: :created, location: @book_issue }
      else
        format.html { render :new }
        format.json { render json: @book_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_issues/1
  # PATCH/PUT /book_issues/1.json
  def update
    respond_to do |format|
      if @book_issue.update(book_issue_params)
        format.html { redirect_to @book_issue, notice: 'Book issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_issue }
      else
        format.html { render :edit }
        format.json { render json: @book_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_issues/1
  # DELETE /book_issues/1.json
  def destroy
    @book_issue.destroy
    respond_to do |format|
      format.html { redirect_to book_issues_url, notice: 'Book issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_issue
      @book_issue = BookIssue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_issue_params
      params.require(:book_issue).permit(:bookName, :bookNumber, :firstName, :lastName, :studentIdNo, :dateIssued)
    end
end

app/controllers/book_returns_controller.rb
class BookReturnsController < ApplicationController
  before_action :set_book_return, only: [:show, :edit, :update, :destroy]

  # GET /book_returns
  # GET /book_returns.json
  def index
    @book_returns = BookReturn.all
  end

  # GET /book_returns/1
  # GET /book_returns/1.json
  def show
  end

  # GET /book_returns/new
  def new
    @book_return = BookReturn.new
  end

  # GET /book_returns/1/edit
  def edit
  end

  # POST /book_returns
  # POST /book_returns.json
  def create
    @book_return = BookReturn.new(book_return_params)

    respond_to do |format|
      if @book_return.save
        format.html { redirect_to @book_return, notice: 'Book return was successfully created.' }
        format.json { render :show, status: :created, location: @book_return }
      else
        format.html { render :new }
        format.json { render json: @book_return.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_returns/1
  # PATCH/PUT /book_returns/1.json
  def update
    respond_to do |format|
      if @book_return.update(book_return_params)
        format.html { redirect_to @book_return, notice: 'Book return was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_return }
      else
        format.html { render :edit }
        format.json { render json: @book_return.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_returns/1
  # DELETE /book_returns/1.json
  def destroy
    @book_return.destroy
    respond_to do |format|
      format.html { redirect_to book_returns_url, notice: 'Book return was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_return
      @book_return = BookReturn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_return_params
      params.require(:book_return).permit(:bookName, :bookNumber, :firstName, :lastName, :student_id_no, :dateReturn, :dateIssued, :dueDate)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book  was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :photo)
    end
end

app/controllers/isssues_controller.rb
class IsssuesController < ApplicationController
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def show
    @library = Library.new
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    signed_in? && current_user.role == 'admin'
  end

  def student?
    signed_in? && current_user.role == 'student'
  end
end

app/helpers/book_issues_helper.rb
module BookIssuesHelper
end

app/helpers/book_reservations_helper.rb
module BookReservationsHelper
end

app/helpers/book_returns_helper.rb
module BookReturnsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/isssues_helper.rb
module IsssuesHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/book_issues/_form.html.erb
<div class="container">

<%= form_for(@book_issue) do |f| %>
  <% if @book_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_issue.errors.count, "error") %> prohibited this book_issue from being saved:</h2>

      <ul>
      <% @book_issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col-md-2">
        <%= f.label :book_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :bookName, :placeholder => "Book Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :book_Number %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :bookNumber, :placeholder => "Book Number" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :first_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :firstName, :placeholder => "First Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :last_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :lastName, :placeholder => "Last Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :student_Id_No %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :studentIdNo, :placeholder => "Student Id No." %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :date_Issued %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :dateIssued, :placeholder => "mm/dd/yy" %>
    </div>
  </div><br/><br/><br/>

  <div class="actions">
    <%= f.submit class: "btn-success" %>
  </div>
<% end %>
</div>

app/views/book_issues/edit.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue'%></li>-->
    <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>-->
  <!--</ul>-->

</div>
<br><br>

<div class="container">
  <div class="hover col-md-12">
  <h1>Editing Book Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_issue, class: "btn btn-info" %> |
<%= link_to 'Back', book_issues_path, class: "btn btn-default" %>
</div>
</div>

app/views/book_issues/index.html.erb
  <div class="container">

    <div class="container">
      <!--<ul class="kj">-->
        <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
        <!--<li class="li"><%= link_to 'Book Issue'%></li>-->
        <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
        <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>-->

      <!--</ul>-->

    </div>
  <br><br>
  <div class="hover col-md-12">
<p id="notice"><%= notice %></p>

<h1 class="text-center">Listing Book Issues</h1>
<br>

<table class="table table-bordered">

  <thead>
    <tr>
      <th class="s">Book Name</th>
      <th class="s">Book Number</th>
      <th class="s">First Name</th>
      <th class="s">Last Name</th>
      <th class="s">Student Id No.</th>
      <th class="s">Date Issued</th>
      <th colspan="3" class="s">Option</th>
    </tr>
  </thead>

  <tbody>
    <% @book_issues.each do |book_issue| %>
      <tr>
        <td><%= book_issue.bookName %></td>
        <td><%= book_issue.bookNumber %></td>
        <td><%= book_issue.firstName %></td>
        <td><%= book_issue.lastName %></td>
        <td><%= book_issue.studentIdNo %></td>
        <td><%= book_issue.dateIssued %></td>
        <td class="s"><%= link_to 'Show', book_issue, class: "btn btn-info" %></td>
        <td class="s"><%= link_to 'Edit', edit_book_issue_path(book_issue), class: "btn btn-warning" %></td>
        <td class="s"><%= link_to 'Destroy', book_issue, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

   <strong><%= link_to 'New Book Issue >>', new_book_issue_path, class: "btn btn-primary" %></strong><br><br>
  </div>
</div>
  <br><br><br><br><br><br>

app/views/book_issues/new.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue' %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>-->
  <!--</ul>-->

</div>
<br><br><br><br>

<div class="container">
  <div class="well">
    <table class="table table-responsive">
      <thead>
      <div>
        <p class="h1 text-center">SMNHS LIBRARY SYSTEM</p>
      </div>
      <div>
        <p colspan="5" class="h2 text-center">Book Issues</p>
      </div>
      </thead>
      <tbody>
      <div class="col-md-12">
        <div class="col-md-6 hover"><br/><br/><br/>

          <%= render 'form' %><br/>

        </div><br><br/><br/>
        <div class="col-md-6">
          <div class="col-md-12">
            <div class="center-block">
              <div class="well alert-danger">
                <h2>Reminder:</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nam
                  possimus veniam? Commodi delectus error est explicabo illo itaque provident
                  ratione rem tenetur veritatis. Ad est explicabo facere impedit nemo.</p>
              </div>
            </div>
            <%= link_to 'Show the Book Issued >>', book_issues_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      </tbody>
    </table>
  </div>
</div>

</div>

app/views/book_issues/show.html.erb
<div class="container">
  <div class="container">
    <ul class="kj">
      <li class="li"><%= link_to 'Book Details', transactions_details_path %></li>
      <li class="li"><%= link_to 'Book Issue' %></li>
      <li class="li"><%= link_to 'Book Returns', book_returns_new_path %></li>
      <li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>
    </ul>
  </div>
  <br><br><br><br>
  <div class="hover col-md-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Book Name:</strong>
  <%= @book_issue.bookName %>
</p>
<br><br>
<p>
  <strong>Book Number:</strong>
  <%= @book_issue.bookNumber %>
</p>
    <br><br>
<p>
  <strong>First Name:</strong>
  <%= @book_issue.firstName %>
</p>
    <br><br>
<p>
  <strong>Last Name:</strong>
  <%= @book_issue.lastName %>
</p>
    <br><br>
<p>
  <strong>Student Id No:</strong>
  <%= @book_issue.studentIdNo %>
</p>
    <br><br>
<p>
  <strong>Date Issued:</strong>
  <%= @book_issue.dateIssued %>
</p>
    <br><br>
<strong><%= link_to 'Edit', edit_book_issue_path(@book_issue), class: "btn btn-warning" %> |
<%= link_to 'Back', book_issues_path, class: "btn btn-default" %></strong>
</div>
</div>
<br><br><br><br><br><br>

app/views/book_returns/_form.html.erb
<div class="container">
<%= form_for(@book_return) do |f| %>
  <% if @book_return.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_return.errors.count, "error") %> prohibited this book_return from being saved:</h2>

      <ul>
      <% @book_return.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :book_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :bookName, :placeholder => "Book Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :book_Number %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :bookNumber, :placeholder => "Book Number" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :first_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :firstName, :placeholder => "First Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :last_Name %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :lastName, :placeholder => "Last Name" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :student_id_no %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :student_id_no, :placeholder => "Student Id No." %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :date_Return %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :dateReturn, :placeholder => "mm/dd/yy" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :date_Issued %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :dateIssued, :placeholder => "mm/dd/yy" %>
    </div>
  </div><br/>

  <div class="field">
    <div class="col-md-2">
      <%= f.label :due_Date %>
    </div>
    <div class="col-md-2">
      <%= f.text_field :dueDate, :placeholder => "mm/dd/yy" %>
    </div>
  </div><br/><br/><br/>

  <div class="actions">
    <%= f.submit class: "btn-success"%>
  </div>
<% end %>
</div>

app/views/book_returns/edit.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue', book_issues_new_path%></li>-->
    <!--<li class="li"><%= link_to 'Book Returns' %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>-->
  <!--</ul>-->
</div>
<br><br>
<div class="container">
  <div class="hover col-md-12">
<h1>Editing Book Return</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_return %> |
<%= link_to 'Back', book_returns_path %>
</div>
</div>

app/views/book_returns/index.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue',book_issues_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns' %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path%></li>-->
  <!--</ul>-->
</div>
<br><br><br>
<div class="container">
  <div class="hover col-md-12">
<p id="notice"><%= notice %></p>
<h1 class="text-center">Listing Book Returns</h1>
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="f">Bookname</th>
      <th class="f">Booknumber</th>
      <th class="f">Firstname</th>
      <th class="f">Lastname</th>
      <th class="f">Student id no</th>
      <th class="f">Datereturn</th>
      <th class="f">Dateissued</th>
      <th class="f">Duedate</th>
      <th colspan="3" class="f">Option</th>
    </tr>
  </thead>

  <tbody>
    <% @book_returns.each do |book_return| %>
      <tr>
        <td><%= book_return.bookName %></td>
        <td><%= book_return.bookNumber %></td>
        <td><%= book_return.firstName %></td>
        <td><%= book_return.lastName %></td>
        <td><%= book_return.student_id_no %></td>
        <td><%= book_return.dateReturn %></td>
        <td><%= book_return.dateIssued %></td>
        <td><%= book_return.dueDate %></td>
        <td class="f"><%= link_to 'Show', book_return, class: "btn btn-info"%></td>
        <td class="f"><%= link_to 'Edit', edit_book_return_path(book_return), class: "btn btn-warning" %></td>
        <td class="f"><%= link_to 'Destroy', book_return, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'New Book Return >> ', new_book_return_path, class: "btn btn-primary" %></strong><br><br>
</div>
</div>
<br><br><br><br><br><br>

app/views/book_returns/new.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue',book_issues_new_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Returns' %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation',book_reservations_new_path %></li>-->
  <!--</ul>-->
</div>
<br><br><br><br>

<div class="container">
  <div class="well">
    <table class="table table-responsive">
      <thead>
      <div>
        <p class="h1 text-center">SMNHS LIBRARY SYSTEM</p>
      </div>
      <div>
        <p colspan="5" class="h2 text-center">Book Returns</p>
      </div>
      </thead>
      <tbody>
      <div class="col-md-12">
        <div class="col-md-6 hover"><br/><br/><br/>

          <%= render 'form' %><br/>

        </div><br><br/><br/>
        <div class="col-md-6">
          <div class="col-md-12">
            <div class="center-block">
              <div class="well alert-danger">
                <h2>Reminder:</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi nam
                  possimus veniam? Commodi delectus error est explicabo illo itaque provident
                  ratione rem tenetur veritatis. Ad est explicabo facere impedit nemo.</p>
              </div>
            </div>
            <%= link_to 'Show the Book Return >>', book_returns_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      </tbody>
    </table>
  </div>
</div>
</div>

app/views/book_returns/show.html.erb
<div class="container">
  <!--<ul class="kj">-->
    <!--<li class="li"><%= link_to 'Book Details', transactions_details_path %></li>-->
    <!--<li class="li"><%= link_to 'Book Issue', book_issues_new_path%></li>-->
    <!--<li class="li"><%= link_to 'Book Returns' %></li>-->
    <!--<li class="li"><%= link_to 'Book Reservation', book_reservations_new_path %></li>-->
  <!--</ul>-->

</div>
<br><br><br><br>
<div class="container">
  <div class="hover col-nd-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Bookname:</strong>
  <%= @book_return.bookName %>
</p>
    <br>
<p>
  <strong>Booknumber:</strong>
  <%= @book_return.bookNumber %>
</p>
    <br>
<p>
  <strong>Firstname:</strong>
  <%= @book_return.firstName %>
</p>
    <br>
<p>
  <strong>Lastname:</strong>
  <%= @book_return.lastName %>
</p>
    <br>
<p>
  <strong>Student id no:</strong>
  <%= @book_return.student_id_no %>
</p>
    <br>
<p>
  <strong>Datereturn:</strong>
  <%= @book_return.dateReturn %>
</p>
    <br>
<p>
  <strong>Dateissued:</strong>
  <%= @book_return.dateIssued %>
</p>
    <br>
<p>
  <strong>Duedate:</strong>
  <%= @book_return.dueDate %>
</p>
    <br>
<strong><%= link_to 'Edit', edit_book_return_path(@book_return), class: "btn btn-warning" %> |
<%= link_to 'Back', book_returns_path, class: "btn btn-default" %></strong>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_for(@book, html: { multipart: true }) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :photo %><br>
      <%= f.file_field :photo %>
    </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container"><br><br>
  <div class="col-md-12 hover">

  <h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>
</div>
    </div>

app/views/books/index.html.erb
<div class="container"></br>
  <div class="col-md-12 hover">

    <% @books.each do |book| %>
        <div class="col-md-3 margin">
          <div>
            <br><br>
            <%= image_tag book.photo if defined?book.photo %>
          </div>
          <br>
          <div class="kj">
            <p>Title: <em><%= book.title %></em></p>
            <p>Author: <em><%= book.author %></em></p>
            <p>Description: <em><%= book.description %></em></p>

            <% if admin? %>
                <%= link_to "Issued", book_issues_new_path %> |
                <%= link_to "Return", book_returns_new_path %> |
                <%= link_to "Reserve", book_reservations_new_path %><br/><br/>

                <%= link_to 'New Book', '/books/new' %> |
                &nbsp;<%= link_to 'Destroy', book,  method: :delete, data: { confirm: 'Are you sure?' } %> |
                <%= link_to 'Edit', edit_book_path(book)%>

            <% elsif student? %>
                <%= link_to "Reserve", book_reservations_new_path, class: 'btn btn-success' %><br/><br/>
            <% else %>
                <%= link_to "Reserve", book_reservations_new_path, class: 'btn btn-success'%><br/><br/>
          <% end %>
          </div>
        </div>
    <% end %>
    <br><br>
  </div>
</div>
<br/>

app/views/books/new.html.erb
<div class="container"><br><br><br>
  <div class="col-md-12 hover">

  <h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>
</div>
    </div>

app/views/books/show.html.erb
<div class="container">
  <br><br>
  <div class="col-md-12 hover">

  <p id="notice"><%= notice %></p>
<p>
  <%= image_tag @book.photo if defined?@book.photo %>
</p>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>
    </div>